In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
df.head()

,id_x,car_rel_url_x,datetime_scrape,name,price_x,currency_x,datetime_product,city,day,hour,attributes,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,kilometrage_unit,barter,loan,salon,spare_parts,vip,featured,img_url,id_y,cars_id,car_rel_url_y,datetime,description,price_y,currency_y,owner_name,shop_name,phone,updated,views,vin,car_details_id_x,Ban növü,Buraxılış ili,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,car_details_id_y,car_rel_url,extra_info
0,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,2024-09-13 20:32:19.751157+00,Hyundai i30,15000.0,AZN,"Bakı, dünən 23:28",bakı,13.09.2024,23:28,"2008, 1.6 L, 270 000 km",2008,1.6,L,270000,km,NaN,NaN,NaN,NaN,NaN,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,2024-09-13 20:40:28.618345+00,Salam orjinal probeqdir bir ildi bizdedir biri...,15000.0,AZN,Şəmi,NaN,507687355.0,13.09.2024,492,NaN,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,"Hetçbek, 5 qapı",2008,NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,/autos/8748840-hyundai-i30,Yüngül lehimli disklər* ABS* Mərkəzi qapanma* ...
1,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,2024-09-13 20:32:19.751157+00,LADA (VAZ) Niva Travel,23700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,"2024, 1.7 L, 0 km",2024,1.7,L,0,km,NaN,NaN,Salon,NaN,vipped-icon,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,2024-09-13 20:40:28.618345+00,LADA Niva Travel modelini nəğd və ya sərfəli l...,23700.0,AZN,NaN,Lada Azərbaycan,554092445.0,13.09.2024,60189,NaN,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,"Offroader / SUV, 5 qapı",2024,Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,/autos/8475807-lada-vaz-niva-travel,Yüngül lehimli disklər* ABS* Kondisioner* Otur...
2,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2024-09-13 20:32:19.751157+00,Toyota Land Cruiser,35600.0,$,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,"2011, 4.0 L, 164 750 km",2011,4.0,L,164750,km,NaN,NaN,NaN,NaN,vipped-icon,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,22bb3704-ebe7-4357-ba2f-1806d1a7042b,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2024-09-13 20:40:28.618345+00,Bezkraska.Mashinda hec bir problem yoxdur.Alve...,35600.0,USD,Anar,NaN,502126242.0,13.09.2024,2473,NaN,22bb3704-ebe7-4357-ba2f-1806d1a7042b,"Offroader / SUV, 5 qapı",2011,Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,164 750 km,Tam,Bakı,22bb3704-ebe7-4357-ba2f-1806d1a7042b,/autos/8739686-toyota-land-cruiser,Yüngül lehimli disklər* ABS* Lyuk* Mərkəzi qap...
3,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,2024-09-13 20:32:19.751157+00,Hyundai Elantra,26700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,"2018, 2.0 L, 126 000 km",2018,2.0,L,126000,km,NaN,NaN,NaN,NaN,vipped-icon,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,e0d16dac-4091-4417-916e-cadeff600f95,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,2024-09-13 20:40:28.618345+00,2019 alış\n,26700.0,AZN,Babək,NaN,774999004.0,13.09.2024,3727,5NPD84LFXKH406133,e0d16dac-4091-4417-916e-cadeff600f95,Sedan,2018,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,126 000 km,Ön,Bakı,e0d16dac-4091-4417-916e-cadeff600f95,/autos/8712597-hyundai-elantra,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
4,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,2024-09-13 20:32:19.751157+00,Toyota Prius,10500.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,"2007, 1.5 L, 354 000 km",2007,1.5,L,354000,km,NaN,NaN,NaN,NaN,vipped-icon,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,82078856-0d07-4a0d-8123-69c2e5002e07,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,2024-09-13 20:40:28.618345+00,"Maşında problem yoxdur. Motor, ABS və batareya...",10500.0,AZN,Natiq,NaN,517264995.0,13.09.2024,446,NaN,82078856-0d07-4a0d-8123-69c2e5002e07,Liftbek,2007,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,354 000 km,Ön,Bakı,82078856-0d07-4a0d-8123-69c2e5002e07,/autos/8674773-toyota-prius,Arxa görüntü kamerası

In [5]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [6]:
df.drop(columns=['id_x','car_rel_url_x','datetime_scrape','datetime_product',
                 'img_url','id_y','cars_id','car_rel_url_y','datetime','car_details_id_x','car_details_id_y','car_rel_url'],inplace=True)

In [7]:
df.head(2)

,name,price_x,currency_x,city,day,hour,attributes,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,kilometrage_unit,barter,loan,salon,spare_parts,vip,featured,description,price_y,currency_y,owner_name,shop_name,phone,updated,views,vin,Ban növü,Buraxılış ili,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,extra_info
0,Hyundai i30,15000.0,AZN,bakı,13.09.2024,23:28,"2008, 1.6 L, 270 000 km",2008,1.6,L,270000,km,NaN,NaN,NaN,NaN,NaN,NaN,Salam orjinal probeqdir bir ildi bizdedir biri...,15000.0,AZN,Şəmi,NaN,507687355.0,13.09.2024,492,NaN,"Hetçbek, 5 qapı",2008,NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı,Yüngül lehimli disklər* ABS* Mərkəzi qapanma* ...
1,LADA (VAZ) Niva Travel,23700.0,AZN,bakı,13.09.2024,23:59,"2024, 1.7 L, 0 km",2024,1.7,L,0,km,NaN,NaN,Salon,NaN,vipped-icon,featured-icon,LADA Niva Travel modelini nəğd və ya sərfəli l...,23700.0,AZN,NaN,Lada Azərbaycan,554092445.0,13.09.2024,60189,NaN,"Offroader / SUV, 5 qapı",2024,Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı,Yüngül lehimli disklər* ABS* Kondisioner* Otur...

In [8]:
df.drop(columns=['price_y', 'currency_x','engine_displacement_num','attributes','engine_displacement_unit',
                 'kilometrage_unit','updated','views','phone','vin','owner_name','shop_name'],inplace=True)

In [9]:
df.isnull().sum()

name                             0
price_x                          0
city                             0
day                              0
hour                             0
production_year                  0
kilometrage_num                  0
barter                      428168
loan                        490381
salon                       460382
spare_parts                 651959
vip                         364780
featured                    489886
description                  15529
currency_y                       0
Ban növü                         0
Buraxılış ili                    0
Hansı bazar üçün yığılıb    189505
Marka                            0
Model                            1
Mühərrik                         0
Qəzalı                      651960
Rəng                             0
Sahiblər                    221621
Sürətlər qutusu                  0
Vəziyyəti                        3
Yeni                             0
Yerlərin sayı               165831
Yürüş                            0
Ötürücü                          0
Şəhər                            0
extra_info                       0
dtype: int64

In [10]:
df.loc[
    df['Qəzalı'].isna() &
    (df['spare_parts'] == 'Qəzalı'),
    'Qəzalı'
] = 'Bəli'

df.drop(columns=['spare_parts'],inplace=True)

In [11]:
df['Model'] = df['Model'].fillna(df['Model'].mode()[0])

df['Vəziyyəti'] = df['Vəziyyəti'].fillna(df['Vəziyyəti'].mode()[0])

In [12]:
df['Sahiblər'] = df['Sahiblər'].fillna('Məlum deyil')

In [13]:
for col in ['barter','loan','salon','vip','featured']:
    df[col] = df[col].fillna('Xeyr')

In [14]:
df['Hansı bazar üçün yığılıb']=df['Hansı bazar üçün yığılıb'].fillna('Məlum deyil')
df['Qəzalı']=df['Qəzalı'].fillna('Məlum deyil')

In [15]:
df['Yerlərin sayı'] = df.groupby('Model')['Yerlərin sayı'].transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else 5))

C:\Users\Macidli\AppData\Local\Temp\ipykernel_36124\1572488698.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Yerlərin sayı'] = df.groupby('Model')['Yerlərin sayı'].transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else 5))

In [16]:
df['has_description'] = df['description'].notna().astype(int)
df.drop(columns=['description'], inplace=True)

In [17]:
df['extra_info_count'] = df['extra_info'].str.count(r'\*') + 1
df.drop(columns=['extra_info'], inplace=True)

In [18]:
rates = {
    'AZN': 1.0,
    'USD': 1.7,
    'EUR': 2.0
}

df['price_azn'] = df['price_x'] * df['currency_y'].map(rates)

df.drop(columns=['city','price_x','name','Buraxılış ili','Yürüş'],inplace=True)

In [19]:
df['Yeni'] = df['Yeni'].map({'Xeyr':0, 'Bəli':1})

df['barter'] = (df['barter'] != 'Xeyr').astype(int)
df['loan'] = (df['loan'] != 'Xeyr').astype(int)

In [20]:
df['salon'] = (df['salon'] != 'Xeyr').astype(int)
df['vip'] = (df['vip'] != 'Xeyr').astype(int)
df['featured'] = (df['featured'] != 'Xeyr').astype(int)

In [21]:
df['day'] = pd.to_datetime(df['day'], format='%d.%m.%Y')
df['month'] = df['day'].dt.month
df['weekday'] = df['day'].dt.weekday

In [22]:
df.drop(columns=['day'], inplace=True)

In [23]:
df['hour_num'] = df['hour'].str.split(':').str[0].astype(int)

In [24]:
df.drop(columns=['hour'], inplace=True)

In [25]:
df['Sahiblər'] = df['Sahiblər'].replace({
    'Məlum deyil': -1,
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4 və daha çox': 4
}).astype(int)

C:\Users\Macidli\AppData\Local\Temp\ipykernel_36124\3386711470.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sahiblər'] = df['Sahiblər'].replace({

In [26]:
df['Yerlərin sayı'] = df['Yerlərin sayı'].replace({
    '8+': 8
}).astype(int)

In [27]:
parts = df['Mühərrik'].astype(str).str.split('/', expand=True)

In [28]:
df['engine_size'] = pd.to_numeric(
    parts[0].str.extract(r'([\d.]+)')[0],
    errors='coerce'
)

In [29]:
df['horsepower'] = pd.to_numeric(
    parts[1].str.extract(r'(\d+)')[0],
    errors='coerce'
)

In [30]:
df['fuel_type'] = parts[2].str.strip()
df['fuel_type'] = df['fuel_type'].fillna('Məlum deyil')

In [31]:
df.drop(columns=['Mühərrik'], inplace=True)

In [32]:
df.head()

,production_year,kilometrage_num,barter,loan,salon,vip,featured,currency_y,Ban növü,Hansı bazar üçün yığılıb,Marka,Model,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Ötürücü,Şəhər,has_description,extra_info_count,price_azn,month,weekday,hour_num,engine_size,horsepower,fuel_type
0,2008,270000,0,0,0,0,0,AZN,"Hetçbek, 5 qapı",Məlum deyil,Hyundai,i30,Məlum deyil,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",0,5,Ön,Bakı,1,6,15000.0,9,4,23,1.6,115.0,Dizel
1,2024,0,0,0,1,1,1,AZN,"Offroader / SUV, 5 qapı",Rəsmi diler,LADA (VAZ),Niva Travel,Məlum deyil,Yaşıl,-1,Mexaniki,"Vuruğu yoxdur, rənglənməyib",1,5,Tam,Bakı,1,4,23700.0,9,4,23,1.7,80.0,Benzin
2,2011,164750,0,0,0,1,1,USD,"Offroader / SUV, 5 qapı",Rəsmi diler,Toyota,Land Cruiser,Məlum deyil,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,8,Tam,Bakı,1,8,60520.0,9,4,23,4.0,282.0,Benzin
3,2018,126000,0,0,0,1,0,AZN,Sedan,Məlum deyil,Hyundai,Elantra,Məlum deyil,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",0,5,Ön,Bakı,1,11,26700.0,9,4,23,2.0,150.0,Benzin
4,2007,354000,0,0,0,1,0,AZN,Liftbek,Amerika,Toyota,Prius,Məlum deyil,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",0,5,Ön,Bakı,1,1,10500.0,9,4,23,1.5,76.0,Hibrid

In [33]:
df['fuel_type'].unique()

array(['Dizel', 'Benzin', 'Hibrid', 'Elektro', 'Plug-in Hibrid', 'Qaz',
       'Hidrogen', 'Məlum deyil'], dtype=object)

In [34]:
df['fuel_type'] = df['fuel_type'].replace({
    'Hidrogen': 'Digər',
    'Qaz': 'Digər'
})

In [35]:
df.drop(columns=['currency_y'], inplace=True)

In [36]:
X = df.drop(columns=['price_azn'])

In [37]:
y = df['price_azn']

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler, OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn import metrics as sm
from warnings import filterwarnings
from sklearn.preprocessing import StandardScaler

In [39]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = 42)

In [54]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [41]:
imp_eng = SimpleImputer(strategy='median')
X_train[['engine_size', 'horsepower']] = imp_eng.fit_transform(X_train[['engine_size', 'horsepower']])
X_test[['engine_size', 'horsepower']] = imp_eng.transform(X_test[['engine_size', 'horsepower']])

In [42]:
cat_cols = [
    'Ban növü',
    'Hansı bazar üçün yığılıb',
    'Marka',
    'Model',
    'Qəzalı',
    'Rəng',
    'Sürətlər qutusu',
    'Vəziyyəti',
    'Ötürücü',
    'Şəhər',
    'fuel_type'
]

In [43]:
num_cols = [
    'production_year',
    'kilometrage_num',

    'engine_size', 
    'horsepower',

    'Sahiblər',
    'Yerlərin sayı',
    'extra_info_count',

    'month',
    'weekday',
    'hour_num'
]

In [44]:
bin_cols=['barter','loan','salon','vip','featured','Yeni','has_description']

In [45]:
for col in cat_cols:
    X_train[col] = X_train[col].astype('category')
    X_test[col] = X_test[col].astype('category')

In [46]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\macidli\anaconda3\lib\site-packages (4.7.0)
Requirement already satisfied: narwhals>=1.15 in c:\users\macidli\anaconda3\lib\site-packages (from lightgbm) (2.7.0)
Requirement already satisfied: numpy>=1.21.3 in c:\users\macidli\anaconda3\lib\site-packages (from lightgbm) (2.3.5)
Requirement already satisfied: scipy in c:\users\macidli\anaconda3\lib\site-packages (from lightgbm) (1.16.3)

In [61]:
import lightgbm as lgb
pipeline = Pipeline([
    ('model', lgb.LGBMRegressor(random_state=42))
])

In [62]:
pipeline.fit(X_train, y_train)

[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.226061 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2348
[LightGBM] [Info] Number of data points in the train set: 457604, number of used features: 28
[LightGBM] [Info] Start training from score 42050.402176

Pipeline(steps=[('model', LGBMRegressor(random_state=42))])

In [63]:
y_pred = pipeline.predict(X_test)

In [64]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [67]:
score = r2_score(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mse)

In [68]:
print('score: ',score)
print('mse: ',mse)
print('mae: ',mae)
print('rmse: ',rmse)

score:  0.9824825909636732
mse:  44127108.42406049
mae:  3266.727125275456
rmse:  6642.823829070021

In [69]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [76]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=True), cat_cols)
    ]
)

In [77]:
lin_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

In [79]:
lin_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['production_year',
                                                   'kilometrage_num',
                                                   'engine_size', 'horsepower',
                                                   'Sahiblər', 'Yerlərin sayı',
                                                   'extra_info_count', 'month',
                                                   'weekday', 'hour_num']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ban növü',
                                                   'Hansı bazar üçün yığılıb',
                                                   'Marka', 'Model', 'Qəzalı',
                                                   'Rəng', 'Sürətlər qutusu',
                                                   'Vəziyyəti', 'Ötürücü',
                                                   'Şəhər', 'fuel_type'])])),
                ('model', LinearRegression())])

In [ ]:
y_pred_lin = lin_pipeline.predict(X_test)

In [ ]:
score_linear = r2_score(y_test,y_pred)